version: '3'
services:
  db:
    image: "postgres:9.6.5"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    env_file:
      - env_file
  test_python:
    build: .
    env_file:
      - env_file
    volumes:
      - .:/opt/services/flaskapp/src
    depends_on:
      - db
volumes:
  dbdata: