version: '3'
services:

  python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: py_app

    volumes:
      - ./dlogs:/app/dlogs

    command: ['python', 'test_python.py']

  datadog:
    image: datadog/agent:7
    container_name: datadog_servise
    depends_on:
      - python
    environment:
      - DD_API_KEY=
      - DD_SITE=datadoghq.eu
      - DD_CHECK_RUNNERS=1
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_CONTAINER_EXCLUDE=name:datadog_servise

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
      - /opt/datadog-agent/run:/opt/datadog-agent/run:rw
