"""empty message

Revision ID: a8370dd3b399
Revises: db6a6a18addd
Create Date: 2020-08-13 23:08:55.273720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8370dd3b399'
down_revision = 'db6a6a18addd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('can_review_tasks', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'can_review_tasks')
    # ### end Alembic commands ###
